create database grocery_management;
use grocery_management;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 1. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.
-- How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) as Total_customers
FROM orders;

-- Which customers have placed the highest number of orders?
SELECT c.cust_id, 
       c.cust_name, 
       COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o 
ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;

-- What is the total and average purchase value per customer?
SELECT c.cust_id,
       c.cust_name,
       SUM(od.total_price) AS total_purchase_value,
       ROUND(AVG(od.total_price), 2) AS avg_purchase_value
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC;

-- Who are the top 5 customers by total purchase amount?

SELECT c.cust_id,
       c.cust_name,
       SUM(od.total_price) AS total_purchase_value 
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC limit 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- How many products exist in each category?
select c.cat_name,count(p.prod_id) as count
FROM categories c 
JOIN products p ON c.cat_id = p.cat_id
group by c.cat_name;

-- What is the average price of products by category?
SELECT c.cat_name,
       ROUND(AVG(p.price), 2) AS average_price
FROM categories c 
JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name;

-- Which products have the highest total sales volume (by quantity)?
select p.prod_name,
       sum(od.quantity) as sales_volume
from products p
join order_details od
on od.prod_id = p.prod_id
group by p.prod_id,p.prod_name
order by sales_volume desc;

-- What is the total revenue generated by each product?
select p.prod_name,
       sum(od.total_price) as revenue
from products p
join order_details od
on od.prod_id = p.prod_id
group by p.prod_id,p.prod_name
order by revenue desc;

-- How do product sales vary by category and supplier?
select c.cat_name,s.sup_name,sum(od.total_price) as Total_Price
from categories c
join products p on p.cat_id=c.cat_id
join order_details od on od.prod_id=p.prod_id
join supplier s on s.sup_id=p.sup_id
group by c.cat_name,s.sup_name
order by Total_Price desc;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- ● How many orders have been placed in total?
SELECT COUNT(ord_id) AS total_orders
FROM orders;
-- ● What is the average value per order?
select round(avg(order_total),2) as avg_order_value
from
(
select ord_id,
       sum(total_price) as order_total
from order_details
group by ord_id
) t;

-- ● On which dates were the most orders placed?
select order_date,count(*) as total_orders
from orders
group by order_date
order by total_orders desc ;

-- ● What are the monthly trends in order volume and revenue?
SELECT DATE_FORMAT(
           STR_TO_DATE(o.order_date, '%m/%d/%Y'),
           '%Y-%m'
       ) AS month,
       COUNT(DISTINCT o.ord_id) AS order_volume,
       ROUND(SUM(od.total_price), 2) AS total_revenue
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;
-- ● How do order patterns vary across weekdays and weekends?
SELECT
    CASE
        WHEN DAYOFWEEK(STR_TO_DATE(order_date,'%m/%d/%Y')) IN (1,7)
        THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY day_type;



-- 4. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- ● How many suppliers are there in the database?
select count(sup_id) from supplier;
-- ● Which supplier provides the most products?
select s.sup_name,
       count(p.prod_id) as total_products
from supplier s
join products p
on s.sup_id=p.sup_id
group by s.sup_id,s.sup_name
order by total_products desc;
-- ● What is the average price of products from each supplier?
select s.sup_name,avg(p.price) as Average_price
from supplier s
join products p on s.sup_id=p.sup_id
group by s.sup_id;

-- ● Which suppliers contribute the most to total product sales (by revenue)?
select s.sup_name,sum(od.total_price) as total_revenue
from supplier s
join products p on s.sup_id=p.sup_id
join order_details od on p.prod_id=od.prod_id
group by s.sup_name
order by total_revenue desc limit 1;

-- 5. Employee Performance
-- Assess how employees are handling and influencing sales.
-- ● How many employees have processed orders?
select count(distinct emp_id)
from orders;
-- ● Which employees have handled the most orders?
select e.emp_name ,count(o.ord_id) as count
from employees e
join orders o on e.emp_id=o.emp_id
group by e.emp_id
order by count desc;

-- ● What is the total sales value processed by each employee?
select e.emp_name,sum(od.total_price) Total_Sales
from employees e
join orders o on o.emp_id=e.emp_id
join order_details od on od.ord_id=o.ord_id
group by e.emp_id;
-- ● What is the average order value handled per employee?
SELECT e.emp_name,
       ROUND(AVG(order_total),2) AS avg_order_value
FROM employees e
JOIN (
    SELECT o.emp_id,
           o.ord_id,
           SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od
    ON o.ord_id = od.ord_id
    GROUP BY o.emp_id,o.ord_id
) t
ON e.emp_id = t.emp_id
GROUP BY e.emp_id,e.emp_name;

-- 6. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- ● What is the relationship between quantity ordered and total price?
select quantity,avg(total_price) from order_details group by quantity order by quantity Asc;

-- ● What is the average quantity ordered per product?
select p.prod_name,round(avg(od.quantity),2) as Avg_Quantity
from products p
join order_details od on od.prod_id=p.prod_id
group by p.prod_id;

-- ● How does the unit price vary across products and orders?
select p.prod_id,p.prod_name,round(avg(od.each_price),2) as avg_unit_price
from products p
join order_details od on p.prod_id=od.prod_id
group by p.prod_id,p.prod_name
order by avg_unit_price desc;
